### PR TITLE
Antagomir

### PR DESCRIPTION
**Pull request by antagomir**
Added aliases in the vignette and added md version of the vignette for easy online browsing.

### CODE REVIEW

**Comment by FelixErnst** [comment]
The *.md file is not needed, is it?

**Comment by antagomir** [comment]
md file is not strictly necessary but I have found it handy (in general) to be able to browse package vignettes also while visiting the pkg github site. Can be removed if this is preferred. Then perhaps a note in README for inexperienced users on how/where to find the rendered vignette.

**Comment by FelixErnst** [comment]
The vignette is displayed on the Bioconductor landing page. The content is generated from the Rmd file, so the md file not strictly necessary. If it gets flagged in the review process it can be removed.

**Comment by antagomir** [comment]
Ok, or it can be removed as obsolete once the pkg is in bioc.

**Pull request merged**
